remote_theme: remote_theme: "mmistakes/minimal-mistakes@4.27.1"

title: Notion Markdown Site
baseurl: "/notion-markdown"
url: "https://fredeerock.github.io"
markdown: kramdown
permalink: pretty
exclude: [".github", "venv"]
collections:
  pages:
    output: true
    permalink: /:name/
