remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

title: Notion Markdown Site
markdown: kramdown
permalink: pretty
exclude: [".github"]
collections:
  pages:
    output: true
    permalink: /:path/
